### ISSUE TITLE
Chart Views

### ISSUE THREAD

**Issue by Fatih20** [hannesschulze/optimizer#83] opened 2020-04-04 05:20 UTC
It'd be nice to have charts like gnome system monitor. You could have an option between your regular UI right now and a toggle to turn on chart view.
![Screenshot from 2020-04-04 12-16-54](https://user-images.githubusercontent.com/51940383/78419250-3079f300-766e-11ea-87c2-976f2053526e.png)

**Comment by hannesschulze** [comment] 2020-04-04 07:04
Duplicate of #5

**Closed** 2020-04-04 07:05 UTC
